### ISSUE TITLE
Logical Error

### ISSUE THREAD

**Issue by mahmoodfeiz** [omidgfx/payir-gateway#1]
https://github.com/omidgfx/payir-gateway/blob/12b47c1aed9ffc037267bd9db7b82aae36842e60/src/Omidgfx/Payir.php#L92

Fix by changing `,` to `=>`:

`$parameters = array_merge(['api' => $this->api], $parameters);`

**Comment by omidgfx** [comment]
Thank you, this bug has been fixed now. you can use v1.0.3 now:
https://packagist.org/packages/omidgfx/payir-gateway#v1.0.3
