### ISSUE TITLE
Invalid response structure

### ISSUE THREAD

**Issue by Omid-Zahed** [omidgfx/payir-gateway#3]
https://github.com/omidgfx/payir-gateway/blob/301cdb101f365900a2d2755da5f88c7f1f0bc290/src/Omidgfx/Payir/Response.php#L27

zamani ke status code = 0 hast reponce null hast  va  khata (Invalid response structure) ijad mishe 
moshkel az server hast ke responce null bazgash mide 
dar soorati ke bayad responce zir ro bargardone
{
  "status" : 0,
  "errorCode" : "کد خطا",
  "errorMessage" : "متن پیام خطا"
}

man ino  ba token( test ) kar kardam va nmidonam zamani ke token asli bashe in khataro mide ya na

**Comment by omidgfx** [comment]
#2 It has been fixed. and the video has been uploaded in aparat. you can find the video in readme.


Best Regards.
